const fs = require('fs');
const file = 'src/data/blogs.json';
const blogs = JSON.parse(fs.readFileSync(file, 'utf8'));

const newBlogs = [
  {
    slug: 'how-to-challenge-insurance-claim-rejection-india',
    title: 'How to challenge an insurance claim rejection in India (Step-by-Step Guide)',
    date: new Date().toISOString(),
    categories: ['Claims', 'Guides'],
    summary: 'Got your insurance claim rejected? Don\'t panic. Learn the exact step-by-step process to challenge a rejected claim in India, escalate it correctly, and win your rightful money.',
    content: '<p>Getting an insurance claim rejected when you need it the most can be devastating. However, a rejection is not the end of the road. In India, policyholders have strong rights and multiple escalation mechanisms to challenge unfair claim denials.</p><h3>1. Understand the Reason for Rejection</h3><p>Before taking action, read the rejection letter (repudiation letter) carefully. Insurance companies must state the exact clause under which the claim was denied. Common reasons include non-disclosure of pre-existing diseases, waiting period clauses, or missing documents.</p><h3>2. Gather Your Evidence</h3><p>Collect all relevant documents: the original policy bond, medical records, discharge summaries, and email correspondences. If the insurer claims non-disclosure, gather medical records proving the condition wasn\'t known at the time of policy purchase.</p><h3>3. File a Grievance with the Insurer</h3><p>Write a formal complaint to the insurer\'s Grievance Redressal Officer (GRO). Be objective, quote the policy terms, and attach your evidence. The insurer is mandated to respond within 15 days.</p><h3>4. Approach the Insurance Ombudsman</h3><p>If the GRO rejects your appeal or doesn\'t respond within 30 days, you can approach the Insurance Ombudsman. The Ombudsman is a free, fast-track dispute resolution mechanism. The complaint must be filed within one year of the insurer\'s rejection.</p><h3>5. Legal Action (Consumer Court)</h3><p>If the Ombudsman ruling is unsatisfactory, the final step is filing a case in the Consumer Disputes Redressal Commission. While this takes longer, consumer courts in India are generally pro-consumer in genuine cases.</p><p><strong>Need Expert Help?</strong> As a certified IRDAI professional with 25+ years of experience, I can help you navigate this complex process and recover your rightful claim. <a href="/support">Contact me today</a> for a free consultation.</p>'
  },
  {
    slug: 'why-lic-policies-lapse-recover-funds',
    title: 'Why LIC policies lapse and how to recover your funds after 5+ years',
    date: new Date().toISOString(),
    categories: ['Life Insurance', 'LIC'],
    summary: 'Millions of rupees are lying unclaimed in lapsed LIC policies. Discover the common reasons why policies lapse and the actionable steps you can take to revive them or recover your funds even after 5 years.',
    content: '<p>A lapsed Life Insurance Corporation (LIC) policy is a common scenario for many Indians. Whether due to financial hardship, missed premium notices, or simple forgetfulness, a lapsed policy means losing your life cover. But did you know you might still be able to recover your funds?</p><h3>Why Do Policies Lapse?</h3><p>A policy lapses when the premium is not paid within the grace period (usually 15 to 30 days). Once lapsed, the life cover ceases, and the policyholder loses the benefits outlined in the contract.</p><h3>Can You Revive a Lapsed Policy?</h3><p>Yes. LIC runs special revival campaigns periodically, allowing policyholders to revive their policies with concessions on late fees. Generally, you can revive a policy within 5 years from the date of the first unpaid premium. You will need to pay all accumulated unpaid premiums plus interest, and possibly undergo a medical examination depending on the gap.</p><h3>What If It\'s Been More Than 5 Years?</h3><p>If the revival period has expired, the policy cannot be reinstated. However, this does not mean you have lost all your money. If you have paid premiums for at least 3 full years (or 2 years for newer policies), your policy acquires a "Paid-Up Value" or a "Surrender Value."</p><ul><li><strong>Paid-Up Value:</strong> Your life cover is reduced proportionally based on the number of premiums paid. This reduced sum is payable upon maturity or death.</li><li><strong>Surrender Value:</strong> You can choose to surrender the policy and withdraw the cash value it has accumulated.</li></ul><h3>How to Claim Your Unclaimed Amount</h3><p>LIC has a dedicated portal for checking unclaimed amounts. You can enter your policy number, PAN, and date of birth to check if any funds are due. If yes, you must submit a discharge form along with your KYC documents and a canceled cheque to your home branch.</p><p>Recovering funds from old, lapsed policies can be a bureaucratic maze. If you are struggling to trace your old LIC policies or get your money back, <a href="/support">reach out for professional assistance</a>.</p>'
  },
  {
    slug: 'understanding-insurance-ombudsman-process-india',
    title: 'Understanding the Insurance Ombudsman process: When to file and how to win',
    date: new Date().toISOString(),
    categories: ['Claims', 'Legal'],
    summary: 'The Insurance Ombudsman is a powerful, free tool for policyholders in India. Learn when you are eligible to file a complaint, how the process works, and strategies to ensure a favorable ruling.',
    content: '<p>When an insurance company unfairly rejects your claim or delays settlement, you don\'t necessarily need to hire an expensive lawyer or spend years in consumer court. The Insurance Ombudsman scheme is designed to resolve policyholder grievances quickly, impartially, and free of cost.</p><h3>When Can You Approach the Ombudsman?</h3><p>You cannot approach the Ombudsman directly. You must first exhaust the insurer\'s internal grievance mechanism. You are eligible to file a complaint if:</p><ul><li>You have complained to the insurer\'s Grievance Redressal Officer (GRO) and they rejected it.</li><li>The insurer did not resolve the complaint to your satisfaction.</li><li>The insurer failed to respond within 30 days of receiving your complaint.</li></ul><p>Additionally, the value of the claim (including compensation) must not exceed ₹30 lakhs, and you must file the complaint within one year of the insurer\'s rejection.</p><h3>What Types of Complaints Are Accepted?</h3><p>The Ombudsman handles disputes relating to:</p><ul><li>Delay in settlement of claims.</li><li>Partial or total repudiation of claims.</li><li>Disputes over premium paid or payable.</li><li>Misrepresentation of policy terms at the time of sale.</li><li>Non-issue of insurance documents.</li></ul><h3>How to File the Complaint</h3><p>The process is straightforward. You must file a written complaint (or submit it online via the Bima Bharosa portal) to the Ombudsman office under whose jurisdiction your insurer\'s branch falls, or where you reside. Include all correspondence, policy documents, and a clear timeline of events.</p><h3>How to Win Your Case</h3><p>To maximize your chances of a favorable ruling:</p><ol><li><strong>Document Everything:</strong> Keep every email, letter, and medical record. The Ombudsman relies heavily on documentary evidence.</li><li><strong>Stick to the Facts:</strong> Present a clear, unemotional timeline. Highlight exactly which policy clause the insurer is violating.</li><li><strong>Attend the Hearing:</strong> Be prepared to explain your case logically during the hearing.</li></ol><p>If the Ombudsman rules in your favor, the insurer must comply within 30 days. If the ruling is against you, you still retain the right to approach the consumer courts.</p><p>Preparing a strong case for the Ombudsman requires technical knowledge of insurance laws. For expert representation and guidance, <a href="/support">contact our team today</a>.</p>'
  },
  {
    slug: 'port-health-insurance-without-losing-waiting-period',
    title: 'How to port your health insurance without losing your waiting period benefits',
    date: new Date().toISOString(),
    categories: ['Health Insurance', 'Guides'],
    summary: 'Unhappy with your current health insurance? Porting allows you to switch insurers without losing your accrued waiting period benefits. Follow this guide to ensure a seamless transition.',
    content: '<p>If you are dissatisfied with your current health insurance provider due to poor service, high premiums, or inadequate coverage, you are not stuck. The Insurance Regulatory and Development Authority of India (IRDAI) allows policyholders to "port" (switch) their health insurance policy to another insurer while retaining their accumulated benefits, most notably the waiting period for pre-existing diseases.</p><h3>What is Portability?</h3><p>Portability is the right to transfer your health insurance policy from one insurance company to another. The biggest advantage is that you don\'t lose the time you\'ve already spent serving waiting periods for specific diseases or pre-existing conditions.</p><h3>The Porting Process: Step-by-Step</h3><h4>1. Apply at the Right Time</h4><p>You must apply for portability at least 45 days before your current policy expires. If you apply too close to the renewal date, the new insurer may reject the request.</p><h4>2. Choose the New Insurer and Plan</h4><p>Research and select a plan that better suits your needs. Request the portability form and the proposal form from the new insurer.</p><h4>3. Submit Necessary Documents</h4><p>You will typically need to submit:</p><ul><li>The completed portability and proposal forms.</li><li>Copies of your previous years\' policy documents.</li><li>Claim history (if any).</li><li>Age proof and identity proof.</li></ul><h4>4. The Underwriting Process</h4><p>The new insurer will request your medical and claim history from your current insurer via the IRDAI portal. They may also require you to undergo a medical check-up, especially if you are over a certain age or are requesting a higher sum insured.</p><h4>5. Acceptance or Rejection</h4><p>The new insurer has the right to accept or reject your portability request based on their underwriting guidelines. If they don\'t respond within 15 days of receiving all information, they are bound to accept your application.</p><h3>Crucial Tips to Remember</h3><ul><li><strong>Sum Insured Enhancements:</strong> If you increase your sum insured while porting, the waiting period benefits will only apply to the old sum insured amount. The increased amount will be subject to new waiting periods.</li><li><strong>No Break in Coverage:</strong> Ensure there is no break in your policy during the transition. If your old policy expires before the new one is issued, you might have to pay the premium to the old insurer to keep it active temporarily.</li></ul><p>Porting can be tricky if you have a complex medical history. For a hassle-free transition to a better health insurance plan, <a href="/support">get in touch for expert assistance</a>.</p>'
  }
];

// Check if already appended
const exists = blogs.find(b => b.slug === newBlogs[0].slug);
if (!exists) {
  blogs.push(...newBlogs);
  fs.writeFileSync(file, JSON.stringify(blogs, null, 2));
  console.log('Blogs appended successfully!');
} else {
  console.log('Blogs already exist.');
}
